services:
  rhew.org:
    build:
      context: .
    container_name: rhew.org
    image: rhew.org
    ports:
      - 443:443
    restart: unless-stopped
    volumes:
      - caddy-data:/data
    networks:
      - reverse_proxy
  8ball:
    build:
      context: 8ball
      dockerfile: Dockerfile
    ports:
      - "7283:7283"
    container_name: 8ball
    networks:
      - reverse_proxy
    restart: unless-stopped

networks:
  reverse_proxy:
    driver: bridge

volumes:
  caddy-data:
